name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
    
    - name: Build release binary
      run: cargo build --release --target x86_64-pc-windows-msvc
    
    - name: Create artifacts directory
      run: mkdir artifacts
    
    - name: Copy binary to artifacts
      run: |
        $binaryName = (Get-Content Cargo.toml | Select-String 'name = "(.+)"' | ForEach-Object { $_.Matches[0].Groups[1].Value })
        Copy-Item "target/x86_64-pc-windows-msvc/release/$binaryName.exe" "artifacts/$binaryName-windows-x64.exe"
      shell: powershell
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: artifacts/
        retention-days: 30
